### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by LIFT-Chen** [SJTU-ViSYS/IntelligentUAVChampionshipStage4#1]
你好，catkin build 报如下错误，请问如何解决

error: ‘struct rosbag::RecorderOptions’ has no member named ‘repeat_latched’
         if (options_.repeat_latched)

error: ‘latched_msgs_’ was not declared in this scope
                     latched_msgs_.insert({{subscriber->getTopic(), it2->second}, out});

**Comment by SJTU-ViSYS** [comment]
请问您是在什么系统下进行编译的？

**Comment by LIFT-Chen** [comment]
> 

Ubuntu 18.04 + ros Melodic

**Comment by huzhanming16** [comment]
我也遇到同样的问题，请问解决了吗

**Comment by LIFT-Chen** [comment]
> 我也遇到同样的问题，请问解决了吗

组委会技术人员已联系解决，这个问题出现的原因是ros noetic （ubuntu20.04）的rosbag新增了repeat_latched这一播放选项，因此会导致在noetic下可以编译通过的rosbag player源码放到melodic（ubuntu18.04）下无法正常编译。

解决方法：
直接删掉根目录下CMakeLists.txt的39行
把thirdparty/stage4_rosbag/include/stage4_rosbag/player.h的第180行的list改成vector
把src文件下judgement.cpp的74行改成mlImageStamp_ReciveStamp = mBagPlayer.iImageStamp_ReciveStamp_;
